#pragma once

// swizzle ops 
// + - * / %
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator + (const target_type& lsh, const Swizzle1<has_assign, base_type, target_type, x> rsh) {{ return lsh + target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator - (const target_type& lsh, const Swizzle1<has_assign, base_type, target_type, x> rsh) {{ return lsh - target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator * (const target_type& lsh, const Swizzle1<has_assign, base_type, target_type, x> rsh) {{ return lsh * target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator / (const target_type& lsh, const Swizzle1<has_assign, base_type, target_type, x> rsh) {{ return lsh / target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator % (const target_type& lsh, const Swizzle1<has_assign, base_type, target_type, x> rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(lsh, target_type(rsh)); else return lsh % target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator + (const Swizzle1<has_assign, base_type, target_type, x> lsh, const target_type& rsh) {{ return target_type(lsh) + rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator - (const Swizzle1<has_assign, base_type, target_type, x> lsh, const target_type& rsh) {{ return target_type(lsh) - rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator * (const Swizzle1<has_assign, base_type, target_type, x> lsh, const target_type& rsh) {{ return target_type(lsh) * rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator / (const Swizzle1<has_assign, base_type, target_type, x> lsh, const target_type& rsh) {{ return target_type(lsh) / rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator % (const Swizzle1<has_assign, base_type, target_type, x> lsh, const target_type& rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(target_type(lsh), rsh); else return target_type(lsh) % rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator + (const Swizzle1<has_assign, base_type, target_type, x> lsh, const Swizzle1<has_assign, base_type, target_type, x>& rsh) {{ return target_type(lsh) + target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator - (const Swizzle1<has_assign, base_type, target_type, x> lsh, const Swizzle1<has_assign, base_type, target_type, x>& rsh) {{ return target_type(lsh) - target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator * (const Swizzle1<has_assign, base_type, target_type, x> lsh, const Swizzle1<has_assign, base_type, target_type, x>& rsh) {{ return target_type(lsh) * target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator / (const Swizzle1<has_assign, base_type, target_type, x> lsh, const Swizzle1<has_assign, base_type, target_type, x>& rsh) {{ return target_type(lsh) / target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x> {inline_marco} target_type operator % (const Swizzle1<has_assign, base_type, target_type, x> lsh, const Swizzle1<has_assign, base_type, target_type, x>& rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(target_type(lsh), target_type(rsh)); else return target_type(lsh) % target_type(rsh); }}

template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator + (const target_type& lsh, const Swizzle2<has_assign, base_type, target_type, x, y> rsh) {{ return lsh + target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator - (const target_type& lsh, const Swizzle2<has_assign, base_type, target_type, x, y> rsh) {{ return lsh - target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator * (const target_type& lsh, const Swizzle2<has_assign, base_type, target_type, x, y> rsh) {{ return lsh * target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator / (const target_type& lsh, const Swizzle2<has_assign, base_type, target_type, x, y> rsh) {{ return lsh / target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator % (const target_type& lsh, const Swizzle2<has_assign, base_type, target_type, x, y> rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(lsh, target_type(rsh)); else return lsh % target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator + (const Swizzle2<has_assign, base_type, target_type, x, y> lsh, const target_type& rsh) {{ return target_type(lsh) + rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator - (const Swizzle2<has_assign, base_type, target_type, x, y> lsh, const target_type& rsh) {{ return target_type(lsh) - rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator * (const Swizzle2<has_assign, base_type, target_type, x, y> lsh, const target_type& rsh) {{ return target_type(lsh) * rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator / (const Swizzle2<has_assign, base_type, target_type, x, y> lsh, const target_type& rsh) {{ return target_type(lsh) / rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator % (const Swizzle2<has_assign, base_type, target_type, x, y> lsh, const target_type& rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(target_type(lsh), rsh); else return target_type(lsh) % rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator + (const Swizzle2<has_assign, base_type, target_type, x, y> lsh, const Swizzle2<has_assign, base_type, target_type, x, y>& rsh) {{ return target_type(lsh) + target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator - (const Swizzle2<has_assign, base_type, target_type, x, y> lsh, const Swizzle2<has_assign, base_type, target_type, x, y>& rsh) {{ return target_type(lsh) - target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator * (const Swizzle2<has_assign, base_type, target_type, x, y> lsh, const Swizzle2<has_assign, base_type, target_type, x, y>& rsh) {{ return target_type(lsh) * target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator / (const Swizzle2<has_assign, base_type, target_type, x, y> lsh, const Swizzle2<has_assign, base_type, target_type, x, y>& rsh) {{ return target_type(lsh) / target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y> {inline_marco} target_type operator % (const Swizzle2<has_assign, base_type, target_type, x, y> lsh, const Swizzle2<has_assign, base_type, target_type, x, y>& rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(target_type(lsh), target_type(rsh)); else return target_type(lsh) % target_type(rsh); }}

template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator + (const target_type& lsh, const Swizzle3<has_assign, base_type, target_type, x, y, z> rsh) {{ return lsh + target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator - (const target_type& lsh, const Swizzle3<has_assign, base_type, target_type, x, y, z> rsh) {{ return lsh - target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator * (const target_type& lsh, const Swizzle3<has_assign, base_type, target_type, x, y, z> rsh) {{ return lsh * target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator / (const target_type& lsh, const Swizzle3<has_assign, base_type, target_type, x, y, z> rsh) {{ return lsh / target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator % (const target_type& lsh, const Swizzle3<has_assign, base_type, target_type, x, y, z> rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(lsh, target_type(rsh)); else return lsh % target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator + (const Swizzle3<has_assign, base_type, target_type, x, y, z> lsh, const target_type& rsh) {{ return target_type(lsh) + rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator - (const Swizzle3<has_assign, base_type, target_type, x, y, z> lsh, const target_type& rsh) {{ return target_type(lsh) - rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator * (const Swizzle3<has_assign, base_type, target_type, x, y, z> lsh, const target_type& rsh) {{ return target_type(lsh) * rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator / (const Swizzle3<has_assign, base_type, target_type, x, y, z> lsh, const target_type& rsh) {{ return target_type(lsh) / rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator % (const Swizzle3<has_assign, base_type, target_type, x, y, z> lsh, const target_type& rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(target_type(lsh), rsh); else return target_type(lsh) % rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator + (const Swizzle3<has_assign, base_type, target_type, x, y, z> lsh, const Swizzle3<has_assign, base_type, target_type, x, y, z>& rsh) {{ return target_type(lsh) + target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator - (const Swizzle3<has_assign, base_type, target_type, x, y, z> lsh, const Swizzle3<has_assign, base_type, target_type, x, y, z>& rsh) {{ return target_type(lsh) - target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator * (const Swizzle3<has_assign, base_type, target_type, x, y, z> lsh, const Swizzle3<has_assign, base_type, target_type, x, y, z>& rsh) {{ return target_type(lsh) * target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator / (const Swizzle3<has_assign, base_type, target_type, x, y, z> lsh, const Swizzle3<has_assign, base_type, target_type, x, y, z>& rsh) {{ return target_type(lsh) / target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z> {inline_marco} target_type operator % (const Swizzle3<has_assign, base_type, target_type, x, y, z> lsh, const Swizzle3<has_assign, base_type, target_type, x, y, z>& rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(target_type(lsh), target_type(rsh)); else return target_type(lsh) % target_type(rsh); }}

template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator + (const target_type& lsh, const Swizzle4<has_assign, base_type, target_type, x, y, z, w> rsh) {{ return lsh + target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator - (const target_type& lsh, const Swizzle4<has_assign, base_type, target_type, x, y, z, w> rsh) {{ return lsh - target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator * (const target_type& lsh, const Swizzle4<has_assign, base_type, target_type, x, y, z, w> rsh) {{ return lsh * target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator / (const target_type& lsh, const Swizzle4<has_assign, base_type, target_type, x, y, z, w> rsh) {{ return lsh / target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator % (const target_type& lsh, const Swizzle4<has_assign, base_type, target_type, x, y, z, w> rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(lsh, target_type(rsh)); else return lsh % target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator + (const Swizzle4<has_assign, base_type, target_type, x, y, z, w> lsh, const target_type& rsh) {{ return target_type(lsh) + rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator - (const Swizzle4<has_assign, base_type, target_type, x, y, z, w> lsh, const target_type& rsh) {{ return target_type(lsh) - rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator * (const Swizzle4<has_assign, base_type, target_type, x, y, z, w> lsh, const target_type& rsh) {{ return target_type(lsh) * rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator / (const Swizzle4<has_assign, base_type, target_type, x, y, z, w> lsh, const target_type& rsh) {{ return target_type(lsh) / rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator % (const Swizzle4<has_assign, base_type, target_type, x, y, z, w> lsh, const target_type& rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(target_type(lsh), rsh); else return target_type(lsh) % rsh; }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator + (const Swizzle4<has_assign, base_type, target_type, x, y, z, w> lsh, const Swizzle4<has_assign, base_type, target_type, x, y, z, w>& rsh) {{ return target_type(lsh) + target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator - (const Swizzle4<has_assign, base_type, target_type, x, y, z, w> lsh, const Swizzle4<has_assign, base_type, target_type, x, y, z, w>& rsh) {{ return target_type(lsh) - target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator * (const Swizzle4<has_assign, base_type, target_type, x, y, z, w> lsh, const Swizzle4<has_assign, base_type, target_type, x, y, z, w>& rsh) {{ return target_type(lsh) * target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator / (const Swizzle4<has_assign, base_type, target_type, x, y, z, w> lsh, const Swizzle4<has_assign, base_type, target_type, x, y, z, w>& rsh) {{ return target_type(lsh) / target_type(rsh); }}
template<bool has_assign, typename base_type, typename target_type, uint32_t x, uint32_t y, uint32_t z, uint32_t w> {inline_marco} target_type operator % (const Swizzle4<has_assign, base_type, target_type, x, y, z, w> lsh, const Swizzle4<has_assign, base_type, target_type, x, y, z, w>& rsh) {{ if constexpr(std::is_same_v<target_type, float> || std::is_same_v<target_type, double>) return {math_namespace}::fmod(target_type(lsh), target_type(rsh)); else return target_type(lsh) % target_type(rsh); }}


// += -= *= /= %=
// template<typename rhs_type, typename base_type, typename target_type, uint32_t... sequence> {inline_marco} target_type operator += (Swizzle<true, base_type, target_type, sequence...>& lsh, const rhs_type& rsh) {{ return lsh = lsh + target_type(rsh); }}
// template<typename rhs_type, typename base_type, typename target_type, uint32_t... sequence> {inline_marco} target_type operator -= (Swizzle<true, base_type, target_type, sequence...>& lsh, const rhs_type& rsh) {{ return lsh = lsh - target_type(rsh); }}
// template<typename rhs_type, typename base_type, typename target_type, uint32_t... sequence> {inline_marco} target_type operator *= (Swizzle<true, base_type, target_type, sequence...>& lsh, const rhs_type& rsh) {{ return lsh = lsh * target_type(rsh); }}
// template<typename rhs_type, typename base_type, typename target_type, uint32_t... sequence> {inline_marco} target_type operator /= (Swizzle<true, base_type, target_type, sequence...>& lsh, const rhs_type& rsh) {{ return lsh = lsh / target_type(rsh); }}
// template<typename rhs_type, typename base_type, typename target_type, uint32_t... sequence> {inline_marco} target_type operator %= (Swizzle<true, base_type, target_type, sequence...>& lsh, const rhs_type& rsh) {{ return lsh = lsh % target_type(rsh); }}

// > < <= >= == != 

// + - sign 

// ! bool not 

// undef 
#undef {inline_marco}

// TODO. disable warning 